## 本地图片上传路径
local:
  path: static
mysql:
  path: 127.0.0.1
  port: "3306"
  config: charset=utf8mb4&parseTime=True&loc=Local
  db-name: university
  username: root
  password: 123456
  max-idle-conns: 0
  max-open-conns: 0
  log-mode: ""
  log-zap: false
system:
  addr: 8088
  db-type: mysql
  oss-type: local
  use-multipoint: false
  iplimit-count: 15000
  iplimit-time: 3600
zap:
  level: info
  format: console
  prefix: '[university]'
  director: log
  showLine: true
  encode-level: LowercaseColorLevelEncoder
  stacktrace-key: stacktrace
  log-in-console: true
miniprogram:
  appid: wx43a5a1b3d9800be0
  secret: b943633d27093a3b59719627a5825b3c
