runmode: dev
name: ccsm
log:
  filePath: /Users/monica/Code/university/apis/logs/log.log
http:
  port: 8080
https:
  port: 443
  crt_path: /Users/monica/Code/university/apis/server.crt
  key_path: /Users/monica/Code/university/apis/server.key
mysql:
  master:
    # addr: root:2021mycloth$#@tcp(bj-cdb-3gj25xpe.sql.tencentcdb.com:60392)/cloth?charset=utf8mb4&parseTime=True&loc=Local
    addr: root:123456@tcp(localhost:3306)/university?charset=utf8mb4&parseTime=True&loc=Local
    maxOpenConns: 100
    maxIdleConns: 100
redis:
  host: 172.21.16.4
  password: ABC123456!
  port: 6379
  db: 1
jwt:
  secret: Well wait for our fate
  ttl: 604800
miniApp:
  appid: wxf6dbbf975398cb07
  secret: 20fc93c6283580f1eebbce57d6eda13e
cos:
  domain: https://file-1254182580.cos.ap-beijing.myqcloud.com
pay:
  wx_callback: https://api.letodiy.com/wx/pay/callback
wx_mc:
  id: 1622618717
  apikey: 20fc93c6283580f1eebbce57d6eda13e
scripts:
  synthetic: /data/project/scripts/synthetic.py
